name: Issues Notifier
on:
  issues:
    types: [opened, reopened]
jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Work Weixin Notifier
        uses: jerray/work-weixin-notifier@v1.1.0
        with:
          key: ${{ secrets.weixin_bot_key }}
          content: |
            # 【机器人文档】 <font color="warning">ISSUE</font> [ <font color="info">${{github.event.issue.state}}</font> ] 
            
            > detail ： [${{ github.event.issue.html_url }}](${{ github.event.issue.html_url }})
            > title ： ${{ github.event.issue.title }} 
            > body ： ${{github.event.issue.body}}
            > user ： ${{ github.event.issue.user.login }}
            > attentions ： <@shaohuizuo><@ostwindli> 
           
          type: markdown
          status: ${{ job.status }}
